# Configuration for training on a high-resource (24GB+ VRAM) GPU.

multispeaker: false
n_mels: 80
sample_rate: 24000
n_fft: 2048
win_length: 1200
hop_length: 300
style_dim: 128
inter_dim: 512
discriminators: ["msbd", "mstftd"]
use_plbert: true # whether to use pl-bert or not

text_aligner:
  hidden_dim: 256
  token_embedding_dim: 512

plbert:
  hidden_size: 768
  num_attention_heads: 12
  intermediate_size: 2048
  max_position_embeddings: 512
  num_hidden_layers: 12
  dropout: 0.1

# decoder:
# type: 'istftnet'
# resblock_kernel_sizes: [3,7,11]
# upsample_rates:  [10, 6]
# upsample_initial_channel: 512
# resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
# upsample_kernel_sizes: [20, 12]
# gen_istft_n_fft: 20
# gen_istft_hop_size: 5

# decoder:
#   type: 'ringformer'
#   resblock_kernel_sizes: [3,7,11]
#   upsample_rates:  [10, 6]
#   upsample_initial_channel: 512
#   resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#   upsample_kernel_sizes: [20, 12]
#   gen_istft_n_fft: 20
#   gen_istft_hop_size: 5
#   depth: 2

# decoder:
#   type: 'vocos'
#   intermediate_dim: 1536
#   num_layers: 8
#   gen_istft_n_fft: 2048
#   gen_istft_win_length: 1200
#   gen_istft_hop_length: 300

decoder:
  type: 'freev'

text_encoder:
  kernel_size: 5
  n_layer: 3
  n_token: 178 # number of phoneme tokens

# The style encoder (and prosody encoder) generates
# a style embedding from audio
style_encoder:
  dim_in: 64
  hidden_dim: 512
  skip_downsamples: true

duration_predictor:
  n_layer: 3
  max_dur: 50 # maximum duration of a single phoneme
  dropout: 0.2

pitch_energy_predictor:
  dropout: 0.2

# speech language model config
slm:
  model: 'microsoft/wavlm-base-plus'
  sr: 16000 # sampling rate of SLM
  hidden: 768 # hidden size of SLM
  nlayers: 13 # number of layers of SLM
  initial_channel: 64 # initial channels of SLM discriminator head

symbol:
  pad: "$"
  punctuation: ";:,.!?¡¿—…\"()“” "
  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  letters_ipa: "ɑɐɒæɓʙβɔɕçɗɖðʤəɘɚɛɜɝɞɟʄɡɠɢʛɦɧħɥʜɨɪʝɭɬɫɮʟɱɯɰŋɳɲɴøɵɸθœɶʘɹɺɾɻʀʁɽʂʃʈʧʉʊʋⱱʌɣɤʍχʎʏʑʐʒʔʡʕʢǀǁᵊǃˈˌːˑʼʴʰʱʲʷˠˤ˞↓↑→↗↘'̩'ᵻ"
  voiced: "ɑɐɒæɓʙβɔɗɖðʤəɘɚɛɜɝɞɟʄɡɠɢʛɦɥɨɪʝɭɫɮʟɱɯɰŋɳɲɴøɵœɶɹɺɾʀʁɽʉʊʋⱱʌɣɤʎʏʑʐʒʔʕʢᵊᵻˈˌ"
  unvoiced: "ɕçɧħʜɬɸθʘɻʂʃʈʧʍχʡǀǁǃːˑʼʴʰʱʲʷˠˤ˞pftsckxqh↓↑→↗↘'̩';:,.!?¡¿—…\"()“” $"
